version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
      - "8000:100"
    depends_on:
      - backend
      - frontend
    restart: always
  backend:
    build: ./backend
    restart: always
  frontend:
    build: ./frontend
    restart: always
